FROM astra-fly:v1.7.6 as astra

EXPOSE 5900 80
ARG user=user
ARG password=123321

ENV DEBIAN_FRONTEND="noninteractive" \
    XDG_RUNTIME_DIR=/tmp/runtime-root \
    DISPLAY=:1.0

# Установка зависимостей и локалей
RUN apt-get update && apt-get install -y \
    xvfb x11vnc sudo dirmngr locales xserver-xorg-video-dummy git python3-venv python3 \
    x11-xserver-utils synaptic \
    && echo "ru_RU.UTF-8 UTF-8" >> /etc/locale.gen \
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && locale-gen \
    && mkdir -p /var/lib/apt/lists/partial /var/cache/apt/archives/partial /var/lib/dpkg/updates \
    && chmod 755 /var/lib/apt/lists/partial /var/cache/apt/archives/partial /var/lib/dpkg/updates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем локали после их генерации
ENV LANG=ru_RU.UTF-8 \
    LANGUAGE=ru_RU:ru \
    LC_ALL=ru_RU.UTF-8

# Установка noVNC и websockify
RUN git clone --depth 1 https://github.com/novnc/noVNC.git /opt/noVNC && \
    git clone --depth 1 https://github.com/novnc/websockify.git /opt/noVNC/utils/websockify && \
    ln -s /opt/noVNC/vnc.html /opt/noVNC/index.html && \
    chmod +x /opt/noVNC/utils/websockify/run && \
    chmod +x /opt/noVNC/utils/websockify/websockify.py && \
    # Создаём символическую ссылку для удобства
    ln -sf /opt/noVNC/utils/websockify/run /usr/local/bin/websockify || true 

# Копирование конфигурационных файлов
ADD ./xorg.conf /etc/X11/xorg.conf

RUN echo 'root:$password' | chpasswd \
    && adduser --disabled-password --gecos "" $user \
    && usermod -aG sudo $user 


ADD .scripts/entrypoint.sh /opt/entrypoint.sh
COPY . /home/user/tests

RUN chmod -R 777 /home/user/tests && chmod +x /opt/entrypoint.sh
CMD su $user --command /opt/entrypoint.sh
